"""Fix models AdminInfo

Revision ID: 5180890c5d13
Revises: ade73c8fe1ee
Create Date: 2025-05-20 12:06:27.212318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5180890c5d13'
down_revision: Union[str, None] = 'ade73c8fe1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_info', sa.Column('price_mini_games', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_info', 'price_mini_games')
    # ### end Alembic commands ###
