"""Fix models ticket

Revision ID: 8a4586d4ca61
Revises: 5180890c5d13
Create Date: 2025-05-20 14:32:28.099986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4586d4ca61'
down_revision: Union[str, None] = '5180890c5d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery', 'count_ticket_win')
    op.drop_column('lottery', 'max_count_ticket')
    op.add_column('vip_info', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip_info', 'price')
    op.add_column('lottery', sa.Column('max_count_ticket', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('lottery', sa.Column('count_ticket_win', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
