"""Fix lottery

Revision ID: 96c78b7d7767
Revises: c92249860582
Create Date: 2025-05-20 21:30:27.799027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c78b7d7767'
down_revision: Union[str, None] = 'c92249860582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lottery', 'accumulation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lottery', 'accumulation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
