"""Delete models InfoStatistics

Revision ID: ade73c8fe1ee
Revises: 90fd9b0de9ae
Create Date: 2025-05-20 11:36:56.941679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade73c8fe1ee'
down_revision: Union[str, None] = '90fd9b0de9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_statistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lvl_gain', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name_gain', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count_ruby', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='info_statistics_pkey')
    )
    # ### end Alembic commands ###
